### PR TITLE
Removed unused variables, components and stylings. Modified homepage stylings

### LINKED ISSUE #6: Huge clock position in mobile view
It should be on top of the section in mobile view  or should not be there at all

### PR DESCRIPTION
**Pull request by theCodingJohn**
I also added eslint. 
Some changes on stylings:

Before

After

Before

After

Before

After

Before at 1012px screen width

After 1012px screen width

This fixes #6

### CODE REVIEW

**Comment by theCodingJohn** [comment]
Changed favicon color to #00a4b8

**Comment by theCodingJohn** [comment]
modified and added some eslint rules you've mentioned

**Comment by theCodingJohn** [comment]
i used variables in naming our pages colors, so we can change it all at once

**Comment by theCodingJohn** [comment]
I moved several components on src/pages/index.jsx in another files 'cause it was convoluted

**Comment by theCodingJohn** [comment]
Fixed: extra logo on the sidebar

**Comment by theCodingJohn** [comment]
fixes #4

**Comment by arlukin** [comment]
Looks good, I will merge later.

**Comment by theCodingJohn** [comment]
fix: navbar link hover state color

**Pull request merged**
